name: Java CI with Maven

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  # Job 1: Scansione segreti e credenziali
  secret_scan: 
    name: GitGuardian Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessario per scansionare la cronologia dei commit

      - name: Scan secrets with GitGuardian
        uses: GitGuardian/ggshield-action@2002482fb5990b486be5598ebcf48a8eba393fce
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  # Job 2: Scansione vulnerabilità dipendenze con Snyk
  snyk_scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@12140f4059e244892ae643824a95459a102120dd
        continue-on-error: true # Evita di bloccare la pipeline se trova vulnerabilità ereditate non bloccanti
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  # Job 3: Build, Test e JaCoCo Report
  build:
    name: Build, Test and Quality Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build and run Tests with JaCoCo
      run: mvn -B clean test jacoco:report
    
    - name: SonarQube Cloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: >
        mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Dsonar.organization=roccopagliarulo
        -Dsonar.projectKey=roccopagliarulo_software_dependability_project_commons-collections
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/